[package]
name = "github-alfred-workflow"
version = "0.3.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.70"
constcat = "0.6.0"
itermore = { version = "0.7.1", features = ["std", "sorted"] }
jiff = "0.2.1"
powerpack = { version = "0.7.0", features = ["cache", "logger"] }
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.95"
sha1 = "0.10.5"
strsim = "0.11.0"
ureq = { version = "3.0.6", default-features = false, features = ["native-tls", "json"] }
